name: pet_pal
description: Find and adopt pets or track care routines of your current pets.

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.13.3
  firebase_core: ^2.25.4
  flutter_local_notifications: ^16.1.0

flutter:
  uses-material-design: true
